config/routes.rb
Rails.application.routes.draw do
  resources :appoiments
  resources :patients
  resources :physicians

end

app/models/appoiment.rb
class Appoiment < ActiveRecord::Base

  belongs_to :physician
  belongs_to :patient

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appoiments
  has_many :physicians, through: :appoiments

end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appoiments
  has_many :patients, through: :appoiments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appoiments_controller.rb
class AppoimentsController < ApplicationController
  before_action :set_appoiment, only: [:show, :edit, :update, :destroy]

  # GET /appoiments
  # GET /appoiments.json
  def index
    @appoiments = Appoiment.all
  end

  # GET /appoiments/1
  # GET /appoiments/1.json
  def show
  end

  # GET /appoiments/new
  def new
    @appoiment = Appoiment.new
  end

  # GET /appoiments/1/edit
  def edit
  end

  # POST /appoiments
  # POST /appoiments.json
  def create
    @appoiment = Appoiment.new(appoiment_params)

    respond_to do |format|
      if @appoiment.save
        format.html { redirect_to @appoiment, notice: 'Appoiment was successfully created.' }
        format.json { render :show, status: :created, location: @appoiment }
      else
        format.html { render :new }
        format.json { render json: @appoiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appoiments/1
  # PATCH/PUT /appoiments/1.json
  def update
    respond_to do |format|
      if @appoiment.update(appoiment_params)
        format.html { redirect_to @appoiment, notice: 'Appoiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appoiment }
      else
        format.html { render :edit }
        format.json { render json: @appoiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appoiments/1
  # DELETE /appoiments/1.json
  def destroy
    @appoiment.destroy
    respond_to do |format|
      format.html { redirect_to appoiments_url, notice: 'Appoiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appoiment
      @appoiment = Appoiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appoiment_params
      params.require(:appoiment).permit(:physician_id, :patient_id, :appoiment)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name)
    end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @patients = Patient.all
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
    @patients = Patient.all
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)
    respond_to do |format|
      if @physician.save
        
        params[:patients_ids].each do |id|
          appoiment = @physician.appoiments.build(physician_id: @physician.id , patient_id: id )
          appoiment.save
        end

        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name, :patient_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appoiments_helper.rb
module AppoimentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appoiments/_form.html.erb
<%= form_for(@appoiment) do |f| %>
  <% if @appoiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appoiment.errors.count, "error") %> prohibited this appoiment from being saved:</h2>

      <ul>
      <% @appoiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :physician_id %><br>
    <%= f.number_field :physician_id %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.number_field :patient_id %>
  </div>
  <div class="field">
    <%= f.label :appoiment %><br>
    <%= f.text_field :appoiment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appoiments/edit.html.erb
<h1>Editing Appoiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appoiment %> |
<%= link_to 'Back', appoiments_path %>

app/views/appoiments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appoiments</h1>

<table>
  <thead>
    <tr>
      <th>Physician</th>
      <th>Patient</th>
      <th>Appoiment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appoiments.each do |appoiment| %>
      <tr>
        <td><%= appoiment.physician_id %></td>
        <td><%= appoiment.patient_id %></td>
        <td><%= appoiment.appoiment %></td>
        <td><%= link_to 'Show', appoiment %></td>
        <td><%= link_to 'Edit', edit_appoiment_path(appoiment) %></td>
        <td><%= link_to 'Destroy', appoiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appoiment', new_appoiment_path %>

app/views/appoiments/new.html.erb
<h1>New Appoiment</h1>

<%= render 'form' %>

<%= link_to 'Back', appoiments_path %>

app/views/appoiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician:</strong>
  <%= @appoiment.physician_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appoiment.patient_id %>
</p>

<p>
  <strong>Appoiment:</strong>
  <%= @appoiment.appoiment %>
</p>

<%= link_to 'Edit', edit_appoiment_path(@appoiment) %> |
<%= link_to 'Back', appoiments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExemploRafael</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>

    <ul>
      <% @patients.each do |patient| %>
          <li>
            <%= check_box_tag 'patients_ids[]', patient.id -%>
            <%= patient.name -%>
          </li>
      <% end %>
    </ul>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing Physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Physicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New Physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @physician.name %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>